"""initial database.

Revision ID: 2a55f3af34c1
Revises: 
Create Date: 2022-01-17 04:21:41.328500+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a55f3af34c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokn_addr', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tokn_pk', 'addr_pk'])

    with op.batch_alter_table('user_addr', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_pk', 'addr_pk'])

    with op.batch_alter_table('user_addr_tx', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_pk', 'addr_tx_pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addr_tx', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('user_addr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tokn_addr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
